version: '3'


services: 
    backend:
        build:
            context: ./pycrud/pycrud
        env_file:
            - ./pycrud/pycrud/.env
        command: gunicorn pycrud.wsgi --bind 0.0.0.0:8000
        ports:
            - "8000:8000"
        depends_on:
            - db
    db:
        image: postgres:13-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./postgres/.env
    frontend:
        build:
            context: ./weather-app
        volumes:
            - react_build:/react/build
    nginx:
        build:
            context: ./nginx
        ports:
            - 80:8080
        volumes:
            - react_build:/var/www/react
        depends_on:
            - backend
            - frontend
volumes:
    react_build:
    postgres_data:
